### ISSUE TITLE
Lab 3 - Need to add a line to push the astronaut-finder.yml to docker repositories

### ISSUE THREAD

**Issue by plaroche1978** [openfaas/workshop#101]
In my case, for the astronaut-finder function to work I had to run this command : faas-cli up -f astronaut-finder.  
Before doing that, in the OpenFaaS GUI the function was not ready and when looking at the kubectl logs was receiving this message : Error from server (BadRequest): container "astronaut-finder" in pod "astronaut-finder-7ff4b9cbcd-tqpjh" is waiting to start: image can't be pulled. 

After pushing the docker image into my repositories, everything is working fine.

**Comment by ivanayov** [comment]
@plaroche1978 `faas-cli up` does `push`, unless you pass the `--skip-push` flag.
I see that we don't use `up` there.
For Swarm it's fine as is, but for Kubernetes you're right that this will not work.

Can you please raise a PR against `kubernetes-preview`? (checkout from the same)

**Comment by alexellis** [comment]
@ivanayov can you tackle the PR please?

**Comment by alexellis** [comment]
@rgee0 / @ewilde / @viveksyngh did any of you run into this? If so please could you raise a PR?

**Comment by rgee0** [comment]
@viveksyngh fixed it.  Theres a `push` in there now.  Thanks Vivek.
