### ISSUE TITLE
Question about orchestrator

### ISSUE THREAD

**Issue by dxz149** [openfaas/workshop#106]
Hi all,
I'm new to OpenFaaS and was trying to write a scheduler which chooses to run a function on the sleeping container or a running container and compare the trade offs.
As far as I understand OpenFaas always keeps one container in running state to reduce the warmup time.
Is it possible to change the code for the orchestrator to choose a sleeping or running container?

Thanks

**Comment by viveksyngh** [comment]
Hi, 

By default OpenFaaS runs one instance for each function to keep it warm. But using some configuration you can also enable scale to zero. Please refer to below links.

https://docs.openfaas.com/architecture/autoscaling/#zero-scale 

https://www.openfaas.com/blog/zero-scale/

**Comment by alexellis** [comment]
Thanks for responding Vivek.
