### ISSUE TITLE
Main page: update Tear down/clear link 

### ISSUE THREAD

**Issue by kyeett** [openfaas/workshop#110]
I was going through the tutorial, trying to clean up my OpenFaas installation, and wasn't sure how to do it. I found the [Tear down/ Clear up](https://github.com/kyeett/workshop/blob/master/README.md#tear-down--clear-up)-section, the link points (https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md#stop-and-remove-openfaas) but it seems that the troubleshooting guide has been moved from github to docs.openfaas.com.

I suggest changing the hyperlink from 
https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md#stop-and-remove-openfaas --> https://docs.openfaas.com/deployment/troubleshooting/#uninstall-openfaas

**Comment by alexellis** [comment]
Hi @kyeett I would prefer you to raise a PR for this.

You will however need to sign off your commits. Let me know if you need any help with that. For me I just do `git commit -s` instead of `git commit`. 

Alex

**Comment by kyeett** [comment]
Hi @alexellis. 

I seem to have deleted my old fork where I did the initial pull request, created a new one here: #115 
I created the change directly on github, so I can't commit from the cli. I believe I managed to sign it manually in the commit message. Please have a look.

Best regards,
Magnus

**Comment by rgee0** [comment]
Fixed in #115
