### ISSUE TITLE
Lab 4 - HTTP Header Keys Changed to Proper Case

### ISSUE THREAD

**Issue by sstiglitz** [openfaas/workshop#111]
Within lab 4, it describes how HTTP headers are exposed in the function as environment variables.

> These headers become exposed through environmental variables so they are easy to consume within your function. So any header is prefixed with Http_ and all - hyphens are replaced with an _ underscore.

However, there appears to be additional manipulation being performed to the HTTP Header key. It is being put into proper case. Below is an illustration. 

```bash
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  bcff3a6bc8d066ba26233a0b5b0e2338476988e1
 version: 0.8.5
$ faas-cli deploy --name env --fprocess="env" --image="functions/alpine:latest" --network=func_functions
$ curl -s --header "CAPITAL-HEADER: VALUE_HERE" "http://127.0.0.1:8080/function/env" | grep "Http_Capital_Header"
Http_Capital_Header=VALUE_HERE
```
I tried tracing this back to the function getAdditionalEnvs within https://github.com/openfaas/faas/blob/master/watchdog/handler.go to see if this was intentional, but did not find where the proper case was actually occurring.

If it is deemed intentional, updating the workshop documentation to point this additional item would be great - It was throwing me off in Lab 5 when we were getting the Http_X_GitHub_Event/Http_X_Github_Event value.

**Comment by alexellis** [comment]
Hi @sstiglitz the "proper case" that you're talking about is a result of serialisation by the HTTP packages in the Go stdlb. The rules for changing case are a black box within the Go framework, I would recommend you just test for the headers you expect and if they do not appear as expected, alter the expected value.

I'm not clear on what you would like as an outcome?

If there's a bug in the workshop then please send a PR.

Alex
