### ISSUE TITLE
Task: merge master & kubernetes-preview branches

### ISSUE THREAD

**Issue by alexellis** [openfaas/workshop#112]
## Task: merge master & kubernetes-preview branches

Originally we were unsure how to have two sets of instructions so created two branches. In practice this is becoming hard to manage so I think that these two branches need to be merged together.

There are new instructions about auto-scaling in the master branch so it needs to be done carefully and reviewed to make sure we don't lose any information.

Alex

**Comment by martinbeentjes** [comment]
I can work on this if you'd like!

**Comment by alexellis** [comment]
Please go ahead @martinbeentjes with your PR :+1: 

Check the contribution guide in openfaas/faas before you start so that you don't get caught on the `git commit --signoff` etc.

**Comment by martinbeentjes** [comment]
@alexellis PR #114 is created
