### ISSUE TITLE
output issue for command uname -a when invoked with markdown function.

### ISSUE THREAD

**Issue by sourabhdeshmukh** [openfaas/workshop#132]
I was going through the lab2, and found that.
when I run:
> uname -a | faas-cli invoke markdown

I get output as
    
><p>Linux openfaas.example.com 3.10.0-957.el7.x86<em>64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86</em>64 x86<em>64 x86</em>64 GNU/Linux</p>

    
Due to Emphasis property in markdown.
> x86_64 

does not display correcty

**Comment by alexellis** [comment]
Thanks for letting us know.
