### ISSUE TITLE
Unable to access Prometheus dashboard after port-forward.

### ISSUE THREAD

**Issue by ShravanGeek** [openfaas/workshop#134]
Hi Team,
I have tried your steps for port-forwarding the prometheus to access the dashboard. But I'm unable to do so. 

`POD=$(kubectl get pods -n openfaas -l app=prometheus -o jsonpath="{.items[0].metadata['name']}")`
`kubectl -n openfaas port-forward $POD 9090:9090`
`Forwarding from 127.0.0.1:9090 -> 9090`
`Forwarding from [::1]:9090 -> 9090`

And it's getting hanged there.

My svc displaying stats like this,
`NAMESPACE     NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE`
`openfaas      prometheus          ClusterIP   10.100.247.94   <none>        9090/TCP                 20h`

I installed openfaas using helm chart. Could you please help me out here?

Thanks a lot for your time.

**Comment by alexellis** [comment]
Hi @ShravanGeek 

Thanks for doing the workshop, hope you are enjoying it.

Where you you find these instructions? Can you send a link please?

The dashboard is first accessed via Grafana in Lab 3 using port 3000:

https://github.com/openfaas/workshop/blob/master/lab2.md#kubernetes

Alex

**Comment by alexellis** [comment]
We also have a Slack channel #workshop which may be a good place to get more help.

--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by tshravan86** [comment]
Hi @alexellis . I apologize for the trouble I'm making here. This is where I found the step to port-forward.

[https://github.com/openfaas/workshop/issues/64](https://github.com/openfaas/workshop/issues/64)

I'm new to this and exploring the concepts. Its really interesting. Thanks a lot for your time and consideration.

**Comment by alexellis** [comment]
The instructions you found are not part of the labs, so I wouldn't use them. You will find instructions for forwarding the port in Lab 9 - https://github.com/openfaas/workshop/blob/master/lab9.md#kubernetes

If there is a specific problem with a lab then raise another issue. For further support, please use Slack.

**Comment by alexellis** [comment]
--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by ShravanGeek** [comment]
Hi @alexellis Sure. Thank you for pointing me to the right direction.
