### ISSUE TITLE
Lab 4 Confusing wording around redploying function

### ISSUE THREAD

**Issue by kwojcicki** [openfaas/workshop#135]
https://github.com/openfaas/workshop/blob/master/lab4.md#security-read-only-filesystems at the very end of this section it says:

```
You can now test the fix by running ```faas-cli up``` and the files will be written into /tmp/.
```

In that section of the lab the yaml file being worked on has a different name than the default yaml (instead it is ingest-file.yml). So just running ```faas-cli up``` doesn't work. Changing the wording to redeploy/using the entire command may be helpful :).

Will send out a PR regarding this in a bit :)

**Comment by alexellis** [comment]
I would welcome a pull request for this. Thank you again for your help and feedback
