### ISSUE TITLE
Add lab / steps for envvarsubst

### ISSUE THREAD

**Issue by alexellis** [openfaas/workshop#140]
## Task

Add lab / steps for envvarsubst

## Context

https://github.com/openfaas/faas-cli/pull/626

This has been tracked on Trello since April, but not worked on yet.

I would like a volunteer to put some content together showing how to use the feature. See the docs or README from the CLI for some inspiration.

https://docs.openfaas.com

https://github.com/openfaas/faas-cli

**Comment by burtonr** [comment]
Derek assign: me
