### ISSUE TITLE
Lab 6 | Possible Typo on Ajax Call Calling Figlet

### ISSUE THREAD

**Issue by sriveros95** [openfaas/workshop#143]
(I think) when doing the ajax call to interact with the service figlet it should be ../figlet instead of ./figlet

Or insert the global gateway
```
...
      // Generate button click
      $('#generate').on('click', function() {
        // Execute ajax request
        $.ajax({
          url:'./figlet',
          type:'POST',
...
```

**Comment by alexellis** [comment]
Thanks for the note :+1: 

This is meant as an example rather than a sample so I'll close it out, unless you want to test it?
