### ISSUE TITLE
Lab 5 faas-cli command typo

### ISSUE THREAD

**Issue by jconlon** [openfaas/workshop#152]
Type for faas-cli login flag --username not --user

## Fix 
Replace 

* Now log in: `echo $PASSWORD | faas-cli login -g http://fuh83fhfj.ngrok.io --user=admin --password-stdin`

with 

* Now log in: `echo $PASSWORD | faas-cli login -g http://fuh83fhfj.ngrok.io --username=admin --password-stdin`

**Comment by alexellis** [comment]
Thank you for letting us know
