### ISSUE TITLE
Lab 5: Japanese version has broken image links

### ISSUE THREAD

**Issue by codegold79** [openfaas/workshop#161]
## Expected Behaviour
I should be able to, but currently can't see images located at
- screenshot/WebhookURLSettings.png
- screenshot/WebhookEventsSettings.png
- screenshot/WebhookResponse.png
- screenshot/NewPAT.png

## Current Behaviour
I only see the no-image icon for four images.

## Possible Solution
Fix the links

## Steps to Reproduce (for bugs)
1. Open https://github.com/codegold79/workshop/blob/master/translations/ja/lab5.md
2. Count four broken image links

## Context
It is more difficult to follow a lab without an image to show us what the current state after following instructions.

## Your Environment
Firefox version 71.0

* Docker version ( Full output from: `docker version` ): n/a

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? n/a

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS Catalina

* Link to your project or a code example to reproduce issue:
https://github.com/codegold79/workshop/blob/master/translations/ja/lab5.md

**Comment by alexellis** [comment]
Would you or @kenfdev like to resolve this? I'm not sure that the Japanese translation is being maintained actively.

**Comment by codegold79** [comment]
I can work on this.

**Comment by alexellis** [comment]
Thanks for fixing this for us. I've merged the changes.
