### ISSUE TITLE
Lab 11: Wrong link to Lab 5

### ISSUE THREAD

**Issue by codegold79** [openfaas/workshop#164]
## Expected Behaviour

I should be able to go directly to Lab 5 in master.

## Current Behaviour

Currently, if I click the link to Lab 5 from Lab 11, I end up going to an old version: https://github.com/openfaas/workshop/blob/7f1b0246376b7e4380bb5874655f28254c15f749/lab5.md

## Possible Solution

Update link to point to the master version of Lab 5: https://github.com/openfaas/workshop/blob/master/lab5.md

## Steps to Reproduce (for bugs)

1. Go to lab 11 at https://github.com/openfaas/workshop/blob/master/lab11.md
2. Click on the link to lab 5 toward the bottom of the page

## Context

This confused me because the old version lacks instructions for when using Kubernetes, which is what I was using.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.11.0

* Docker version ( Full output from: `docker version` ): 19.03.5

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS Catalina

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Thank you for finding this, please do send a PR

**Comment by alexellis** [comment]
Thanks again for these changes :+1:
