### ISSUE TITLE
Lab 1 Invalid curl url to install kubectl on Mac

### ISSUE THREAD

**Issue by brp-magnusd** [openfaas/workshop#171]
## Expected Behaviour
Copy paste the commands to install kubectl into a terminal should work on MacOS.

## Current Behaviour
The url to kubectl is incorrect so chmod will fail as the kubctl-file does not exist.

## Possible Solution
Remove `.exe` in `curl -LO https://storage.googleapis.com/kubernetes-release/release/$VER/bin/darwin/amd64/kubectl.exe` will fix the problem.

## Steps to Reproduce (for bugs)

1. Copy paste the commands to install kubectl into a terminal on MacOS.

## Your Environment

MacOS

**Comment by alexellis** [comment]
Thank you
