### ISSUE TITLE
Lab 5 - how do I get the public URL?

### ISSUE THREAD

**Issue by gioargyr** [openfaas/workshop#173]
In Lab5 you say
"Use the built-in UI of ngrok at http://127.0.0.1:4040 to find your HTTP URL. You will be given a URL that you can access over the Internet, it will connect directly to your OpenFaaS API Gateway."

I have ngrok running and it seems that it works fine. I cannot understand how I will get this URL.

Also, 4 lines below, you say:
"export NGROK_ADDRESS=https://fuh83fhfj.ngrok.io"

What is this "https://fuh83fhfj.ngrok.io"?
I am accessing my ngrok by using one of my VMs IP and the port that the NodePort is using.

## Expected Behaviour

N/A

## Current Behaviour

I get:
"
Server returned unexpected status code: 404 - {"status_code":404,"msg":"Not Found","details":{"path":"/system/functions"}}
"
## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. I am just doing what is supposed to do in Lab5. ngrok is running.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.11.8

* Docker version ( Full output from: `docker version` ):
19.03.4

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Kubernetes and OpenFaaS are running on Ubuntu 16.04 machines.
I am running every command on a Debian 10.3 machine

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi, thanks for taking the workshop. I'm not sure what you are missing? What part of the instructions didn't work as expected?

Alex

<img width="944" alt="Screenshot 2020-03-19 at 12 34 05" src="https://user-images.githubusercontent.com/6358735/77068117-f8bc4b80-69dd-11ea-99cd-0fafe6c91e7d.png">

**Comment by alexellis** [comment]
I ran all of those commands and it worked as expected:

<img width="1564" alt="Screenshot 2020-03-19 at 12 36 14" src="https://user-images.githubusercontent.com/6358735/77068293-3caf5080-69de-11ea-91cd-c0411c0a928d.png">

**Comment by Waterdrips** [comment]
I ran the commands just now too and seems to be working.
![image](https://user-images.githubusercontent.com/40488132/77068541-b6473e80-69de-11ea-808f-c9566927602f.png)
