### ISSUE TITLE
Lab 2 Monitoring dashboard port-forwarding incorrect command

### ISSUE THREAD

**Issue by sergevonage** [openfaas/workshop#184]
Port-forwarding command incorrect
```
$ kubectl port-forward deployment/grafana 3000:3000 -n openfaas
```
because we run Grafana in OpenFaaS Kubernetes namespace:
```
kubectl -n openfaas run \
--image=stefanprodan/faas-grafana:4.6.3 \
--port=3000 \
grafana
```
## Expected Behaviour

Port forwards
## Current Behaviour

Error from server (NotFound): deployments.apps "grafana" not found 
## Possible Solution

Update command:
```
$ kubectl port-forward grafana 3000:3000 -n openfaas
```
## Steps to Reproduce (for bugs)

1. Run
```
$ kubectl port-forward deployment/grafana 3000:3000 -n openfaas
```

## Context

Mislead during go through the tutorial
## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  c12d57c39ac4cc6eef3c9bba2fb45113d882432f
 version: 0.12.14
* Docker version ( Full output from: `docker version` ):
Docker version 19.03.13, build 4484c46d9d  
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Fixed in 74f50f4
