### ISSUE TITLE
How to go with a CRUD operation in Java?

### ISSUE THREAD

**Issue by rward27** [openfaas/workshop#186]
I am sorry that I have to write this as an issue but I didn't find more resources for openfaas anywhere and there are not many tutorials doing something more than just pulling pre-built templates and running them.

I was wondering if anyone here could guide me in figuring out how to go with Openfaas (on kubernetes) in performing CRUD operations. Basically I was searching a way to do this in Java but I get lost when it comes to Handler. Do I need to write multiple handlers for each CRUD operation and write specific operation inside each handler?

In case I have 20 Services in my project, each having CRUD operations, do I need to have 20x4=80 handlers for the those services and their CRUD operations?

**Comment by alexellis** [comment]
Hi @rward27 it's a common misconception that every HTTP verb should be its own function. I'm really not sure how people come up with this one.

Use one function per responsibility or entity and switch on the HTTP verb, HTTP path or query string.

Alex
