### ISSUE TITLE
Lab 3: Multiple Issues

### ISSUE THREAD

**Issue by DanielHabenicht** [openfaas/workshop#195]
## Expected Behaviour
The Lab should go through flawlessly

## Current Behaviour
There were some errors or weird behaviours: 
1.  `faas-cli template pull https://github.com/openfaas-incubator/python3-debian` errors, seems like its already integrated in the normal template (https://github.com/openfaas/templates/tree/master/template)
2. `faas-cli template store describe node10-express` errors -> there is no template for it
     - all future uses of `node10-express` are not working, maybe use `powershell` instead?

**Comment by alexellis** [comment]
Hi, for #1, can you change to the golang-http repo instead?

For #2 why not describe `node14`?

Are you happy to send a PR?
Alex

**Comment by alexellis** [comment]
@DanielHabenicht are you still interested in taking this up?

**Comment by alexellis** [comment]
/add label: good first issue, help wanted
