### ISSUE TITLE
installing openfaas with arkade

### ISSUE THREAD

**Issue by dimanzt** [openfaas/workshop#215]
Hi all,
I'm trying to install OpenFaas using arkade.
I have installed docker, Kubernetes and installing OpenFaas gives me the following error:
I'm using Ubuntu 22.04 and docker 23.0.3, Kubernetes v1.24.2.

arkade install openfaas
Using Kubeconfig: /home/zadtoota/.kube/config
[Warning] unable to create secret basic-auth, may already exist: error: failed to create secret secrets "basic-auth" already exists
Client: x86_64, Linux
2023/05/18 23:28:07 User dir established as: /home/zadtoota/.arkade/
WARNING: open /home/zadtoota/.docker/config.json: permission denied
/home/zadtoota/.docker/config.json
github.com/docker/cli/cli/config.load
	github.com/docker/cli@v20.10.21+incompatible/cli/config/config.go:138
github.com/docker/cli/cli/config.Load
	github.com/docker/cli@v20.10.21+incompatible/cli/config/config.go:111
oras.land/oras-go/pkg/auth/docker.NewClientWithDockerFallback
	oras.land/oras-go@v1.2.2/pkg/auth/docker/client.go:86
helm.sh/helm/v3/pkg/registry.NewClient
	helm.sh/helm/v3/pkg/registry/client.go:83
main.newDefaultRegistryClient
	helm.sh/helm/v3/cmd/helm/root.go:277
main.newRootCmd
	helm.sh/helm/v3/cmd/helm/root.go:155
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:66
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1598
WARNING: open /home/zadtoota/.docker/config.json: permission denied
/home/zadtoota/.docker/config.json
github.com/docker/cli/cli/config.load
	github.com/docker/cli@v20.10.21+incompatible/cli/config/config.go:138
github.com/docker/cli/cli/config.Load
	github.com/docker/cli@v20.10.21+incompatible/cli/config/config.go:111
oras.land/oras-go/pkg/auth/docker.NewClientWithDockerFallback
	oras.land/oras-go@v1.2.2/pkg/auth/docker/client.go:86
helm.sh/helm/v3/pkg/registry.NewClient
	helm.sh/helm/v3/pkg/registry/client.go:83
main.newDefaultRegistryClient
	helm.sh/helm/v3/cmd/helm/root.go:277
main.newRootCmd
	helm.sh/helm/v3/cmd/helm/root.go:155
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:66
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1598

Error: exit code 1

Any idea why this is happenning?

**Comment by alexellis** [comment]
Hi @dimanzt sounds a bit like you may be running arkade as root - or perhaps you ran it as root once and now you have messed up permissions? Perhaps there's also an issue with your Helm installation.

I'd suggest checking there first.

We have a huge amount of people using arkade and arkade with openfaas, without issue, so I'm going to close and say it'll be down to your environment.

Alex
