### ISSUE TITLE
Proposal: Some improvements about the workshop

### ISSUE THREAD

**Issue by kenfdev** [openfaas/workshop#27]
First of all, thanks for all the contents of this workshop. It's awesome.
I've been creating the Japanese version and there are some parts I think we should improve.

**The Main [README.md](https://github.com/openfaas/workshop/blob/master/README.md)**

> ... Topics will include: managing dependencies with pip, dealing with API tokens through secure secrets, monitoring functions with Prometheus, invoking functions asynchronously and chaining functions together to create applications. We finish by connecting to online event-streams through IFTTT.com ...

It mentions about secrets and IFTTT.com but currently this workshop does not use secrets and IFTTT.com. I assume secrets are coming soon, but IFTTT.com should be removed imo.

**Typo in command of lab3**

The command fails because it's missing a '\'.

```
$ faas-cli build -f sorter.yml \
  && faas-cli push -f sorter.yml      <- We need a '\' here.
  && faas-cli deploy -f sorter.yml
```

**The appendix**

* It still includes `localhost`. Should be 127.0.0.1

* The non-existing function call returns 404

> Now give it a few seconds and check what you see on the UI. There should be a 500 error for the function name `non-existing-function.

It says 500 but it actually returns 404 when I tried it. (Prometheus metrics, too)

```
Server returned unexpected status code: 404 - Cannot find service: non-existing-function.
```

![image](https://user-images.githubusercontent.com/3941889/38161095-552edf34-3503-11e8-8655-952312c25628.png)

* A mixture of the two techniques

> as documented here is where one function the director exists only to call another function and return the result. It is a mixture of the two techniques we explored above.

I think this should say 

"It is a mixture of the two techniques we explored in Lab6."

"above" was a little confusing for me.

If I should create a PR for this, I will so please ping me if that's the case.
Thanks!

**Comment by alexellis** [comment]
Hi Ken good feedback. Please go ahead and update as you see fit and I'll review.

**Comment by alexellis** [comment]
Re: the 500 vs. 404 error it could be different depending on the back-end provider and OpenFaaS gateway version.

**Comment by alexellis** [comment]
Derek close: work completed
