### ISSUE TITLE
Lab: Show HTML returned from a function

### ISSUE THREAD

**Issue by alexellis** [openfaas/workshop#30]
This task is for a new lab for the workshop. The aim is to show two things: how to set a content_type and how to return HTML from a function.

A function can write HTML in Python easily by setting `content_type: text/html` in the environment section of the YAML file then returning the text needed for the page.

Content:

* Show how to read a static HTML file from disk and return it
 * Show how to read the query string and return two different files i.e. action=list/new
* Show how to generate some basic HTML in a function and return that

This is a Node.js function which gives HTML but the approach is similar in Python: https://github.com/alexellis/html-function/blob/master/make-html/handler.js

**Comment by kenfdev** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Derek close: via #34

**Comment by alexellis** [comment]
@kenfdev please add your page into the ToC in the README and link at the end of Lab 4.
