### ISSUE TITLE
Lab 8 - show auto-scaling in action

### ISSUE THREAD

**Issue by alexellis** [openfaas/workshop#31]
This lab should be short and just show a very simple binary function like "sha512sum" from the image "functions/alpine:latest".

* Show a query for Prometheus (there is some content in the appendix for this)
* Invoke the function with a while/curl statement in bash. We don't want people to have to install Go to try this for (hey) or to need Linux to get the `ab` tool
* Have them look at the alerts page and see Pending/ Firing - have them check the main UI to see the replicas increasing

Also link to the docs page on auto-scaling and explain briefly that min/max replicas can be set too.

Feel free to take some creative license with this but keep it brief so it can be reviewed / merged for the workshop week beginning 9 Apr.

**Comment by Templum** [comment]
I will work on this. Any thing I should keep in mind regarding structure?

**Comment by alexellis** [comment]
Closed via #33

**Comment by alexellis** [comment]
@iyovcheva can you give this a run-through if you can find time?

**Comment by iyovcheva** [comment]
@alexellis I reproduce if only ` com.openfaas.scale.min` is manually set to >1 in the `stack.yml`.
In `docker-compose.yml` it is not configured for `nodeinfo` (I'm not sure about the ` functions/nodeinfo:latest` image) and when I test the lab on my machine, there is only one replica.

**Comment by alexellis** [comment]
@iyovcheva this is working for me - having tested it with you on Zoom. I'd try it once more on your computer - maybe with figlet then move on.
