### ISSUE TITLE
Lab 3 Documentation Glitch for Python3 Template

### ISSUE THREAD

**Issue by zanetworker** [openfaas/workshop#37]
In Lab 3, the mentioned content of `handler.py` are: 

```python
def handle(req):
    """handle a request to the function
    Args:
        req (str): request body
    """

    print(req)
```

However, the actual content after the pull are: 

```python 
def handle(req):
    """handle a request to the function
    Args:
        req (str): request body
    """

    return req
```

the **print** behaviour is replaced by **return**. The documentation states `This function will just print the input, so it's effectively an echo function`, and since it is returned, I am not sure how to is redirected to stdout and where (probably needs a deeper look at the code)

**Comment by alexellis** [comment]
It's not a glitch both work but we should move all the docs to say return instead

**Comment by zanetworker** [comment]
Yup, I meant a glitch in the documentation because pulling produces something and the documentation is saying something else.

**Comment by alexellis** [comment]
Hi I think we have this sorted now @zanetworker - thank you for helping out.
