### ISSUE TITLE
Add notes/examples for Kubernetes

### ISSUE THREAD

**Issue by ivanayov** [openfaas/workshop#42]
All examples in the workshop are now for Swarm.

In [Lab 3](https://github.com/openfaas/workshop/blob/master/lab3.md#hello-world-in-python) we mention in a note that one can also use Kubernetes (there is an example with `export OPENFAAS_URL=127.0.0.1:31112` )

What about including  [Deployment guide for Kubernetes](https://docs.openfaas.com/deployment/kubernetes/) documentation in the workshop? 

This will require some changes to the Labs, f.e. in Lab 4, [Making use of logging](https://github.com/openfaas/workshop/blob/master/lab4.md#making-use-of-logging), we'll need to say how to check the logs with `kubectl`.
Needs reviewing what other sections require changes.

Testing both Swarm and Kubernetes can be confusing for someone trying OpenFaaS for first time.
Separating them may cause duplicating some labs.  May be some middle-ground option would be the best.

**Comment by ericstoekl** [comment]
I would advocate for removing the blurb about Kubernetes in Lab3, and instead expanding Lab1 to include a section about deploying on Kubernetes. It could be exactly the same as the Docker Swarm deployment instructions but cover Kubernetes, and link to the Kubernetes Deployment Guide similarly to how the Swarm Deployment Guide is linked to at the [end of Lab1](https://github.com/openfaas/workshop/blob/master/lab1.md#deploy-openfaas).

The thing that makes this difficult is how frequently `127.0.0.1:8080` is referenced in the following Labs. Could we have a section where we establish that the user needs to find out their IP Address Endpoint, and in the rest of the lab refer to it as `<your-of-endpoint>` or something? Maybe just having them set `OPENFAAS_URL` at the beginning would be a way to accomplish this.

**Comment by alexellis** [comment]
We're going to need a longer term strategy for Kubernetes. Right now Swarm is the easier platform for teaching the workshop - but we could look to add some examples where things vary. Like I think we've already mentioned - those examples shouldn't make the flow confusing.

Suggestions welcome.

**Comment by alexellis** [comment]
Let's put this on hold for now.

**Comment by ivanayov** [comment]
I'm taking Lab 1 and 2.

After discussion with Alex, they are going to be modified with notes for Kubernetes. Notes should include all of Minikube, Docker for Mac and GKE

**Comment by alexellis** [comment]
We won't necessarily be able to merge labs PRs one at a time since it will be confusing, but happy to start at the beginning. 

The initial pass should cover `kubectl create secret` / `kubectl logs` etc. We have a setup guide for Kubernetes in the docs which can be referenced.

**Comment by ivanayov** [comment]
Now working on first 2 labs

**Comment by alexellis** [comment]
Derek close: completed
