### ISSUE TITLE
Typo on code for 'Making use of logging'

### ISSUE THREAD

**Issue by AndyFelton** [openfaas/workshop#46]
Section is referring to hello-openfaas from lab3:

$ faas-cli build -f issue-bot.yml \
  && faas-cli push -f issue-bot.yml \
  && faas-cli deploy -f issue-bot.yml

Should read

$ faas-cli build -f hello-openfaas.yml \
> && faas-cli push -f hello-openfaas.yml \
> && faas-cli deploy -f hello-openfaas.yml

**Comment by alexellis** [comment]
Derek close: fixed/merged
