### ISSUE TITLE
The "gateway" hostname is not resolved

### ISSUE THREAD

**Issue by infominer75** [openfaas/workshop#52]
I am following the workshop where-n we invoke the sentiment analysis function from within a python function using an HTTP GET request. The format of the URL for the GET request is:

``http://gateway:8080/function/sentimentanalysis``

When I deploy this function to my GKE cluster and invoke it, I get the following Python stack trace:

``Traceback (most recent call last):
  File "index.py", line 15, in <module>
    ret = handler.handle(st)
  File "/home/app/function/handler.py", line 11, in handle
    r = requests.get(SENTIMENT_ANALYSIS_FUNCTION, data=test_sentence)
  File "/home/app/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/app/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/app/.local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/app/.local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/app/.local/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gateway', port=8080): Max retries exceeded with url: /function/sentimentanalysis (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f39b73aa9d0>:Failed to establish a new connection: [Errno -2] Name does not resolve',))``

I checked the Pod's /etc/hosts and could not find a DNS entry for gateway that points to the correct Gateway. Additionally, /etc/resolv.conf does not give me much information either ( I do not think that currently this is relevant to the issue I am facing)

Should the Pod getting created automatically contain the DNS entry for "gateway" to point to the OpenFaas gateway?

**Comment by alexellis** [comment]
The workshop is for Swarm and not for Kubernetes, so for Kubernetes (GKE etc) you'll have to adapt the content. Any hostname like the gateway will need a DNS suffix of its namespace so use http://gateway.openfaas:8080

Thanks,

Alex

**Comment by infominer75** [comment]
Thanks Alex. By using the gateway.openfaas (since openfaas is my GKE namespace for openfaas) I was able to make it work.

**Comment by alexellis** [comment]
Great! You can also use the OPENFAAS_URL env-var to set the gateway for the CLI. How did the rest of the tutorial go?
