### ISSUE TITLE
Incomplete instructions for Windows users

### ISSUE THREAD

**Issue by tracymiranda** [openfaas/workshop#54]
There are a couple of points of friction in this lab for windows users:

1. If windows users have default git-bash installed (with use MinTTY specified) they will get an error when they try to run 'docker login' in [lab 1](https://github.com/openfaas/workshop/blob/master/lab1.md) The error seen is "Error: Cannot perform an interactive login from a non TTY device" but has a straightforward workaround.  Refs:
https://willi.am/blog/2016/08/08/docker-for-windows-interactive-sessions-in-mintty-git-bash/
https://dzone.com/articles/docker-on-windows-interactive-tty-session-gives-ca

2. The link in [lab 1](https://github.com/openfaas/workshop/blob/master/lab1.md)  to download the faas-cli.exe client could do with being more direct to save user having to hunt around for the right thing, i.e linking to https://github.com/openfaas/faas-cli/releases

**Comment by alexellis** [comment]
Thank you for taking time to write this up @tracymiranda - it's super useful.

I've addressed the comments in the commit message and changes in ddb6e1e 

Alex

**Comment by tracymiranda** [comment]
👍 Looks great, thanks for quick turnaround.
