### ISSUE TITLE
Lab 11 - Advanced Feature - Trust with HMAC

### ISSUE THREAD

**Issue by alexellis** [openfaas/workshop#61]
Suggested by @martindekov - let's add a lab for using HMAC

The CLI has a new `--sign` feature (in the next release) - this can be used to invoke a function and sign the header at the same time.

I have an example repo that can be used as an example (perhaps translated to Python, or kept in Go?)

We might want to link to some libraries for use with other languages like C#, Ruby & Node.

https://github.com/alexellis/sofia-test1/blob/master/signed-and-sealed/handler.go#L14

**Comment by alexellis** [comment]
Might want to quote from my Golang component's README or link to Wikipedia - https://github.com/alexellis/hmac#how-it-works

cc @rgee0

**Comment by rgee0** [comment]
I found the `env` function useful for demonstrating the feature.  A possible flow might be:

* to introduce the concept of HMAC 
* demonstrate the function env without, and then with, the `--sign` flag to show the effect
* a practical example with a signed-and-sealed function

**Comment by martindekov** [comment]
Ok I will go with the flow pointed above

**Comment by martindekov** [comment]
I was wondering isn't it a good idea to use the `lab5` issue bot function to give the concept of protecting the function and maybe point out if we try invoking with wrong `--sign` flag or invoking altogether what happens? I think this would be ideal showcasing how hmac intercepts if if the hash is mismatched. @rgee0 @ivanayov ?

**Comment by martindekov** [comment]
Otherwise I am giving excess information in things already done in `lab5`.

**Comment by rgee0** [comment]
I'd suggest introducing the concept in lab 5 with something like  _"... when dealing with messages from a third party it is recommended to use a message signing scheme such as HMAC, you can explore this further in Lab 11"_ 

Then in lab 11 fully introduce HMAC and follow the flow we suggested earlier.  Using a simple function initially to demonstrate the effect signing has and then the signed-and-sealed function to show it performing its natural function.

Lab 5 is already quite lengthy and is intended to enable the attendees to create something meaningful to start to stimulate thought on practical applications.  Additionally, in Lab 5 the flow is in the opposite direction to that through which we would demonstrate `--sign`, which given the detail already in Lab 5 might be a little confusing.
