### ISSUE TITLE
Lab 2 - port forwarding for grafana

### ISSUE THREAD

**Issue by pyramation** [openfaas/workshop#69]
I'm using k8s, so I wasn't able to get swarm up. I've translated what is needed for lab 2:

```
kubectl -n openfaas run \
--image=stefanprodan/faas-grafana:4.6.3 \
--port=3000 \
grafana

kubectl -n openfaas expose deployment grafana \
--type=NodePort \
--name=grafana

POD=$(kubectl get pods -n openfaas | grep grafana | awk '{print $1}')
kubectl port-forward -n openfaas $POD 3000:3000
```

**Comment by alexellis** [comment]
We already have this in #64, but thanks for logging your method of port forwarding.

For K8s the instructions have to be adapted as you're doing - but within 2-3 weeks I expect us to have dual instructions ready as per #42 

Thanks again for your input 👍 

Alex

**Comment by alexellis** [comment]
Derek close
