### ISSUE TITLE
Lab 3 - outdated cli?

### ISSUE THREAD

**Issue by pyramation** [openfaas/workshop#70]
when I tried `faas-cli up -f hello-openfaas.yml` I got:

![screen shot 2018-10-03 at 3 58 18 pm](https://user-images.githubusercontent.com/545047/46444110-4f1fc680-c725-11e8-9057-c78cfea8d830.png)

**Comment by alexellis** [comment]
Have you tried updating your CLI version?

The start of the labs have pre-reqs where you install the latest CLI.

Alex

**Comment by alexellis** [comment]
Type in `faas-cli version` and I think you'll find you need to update @pyramation 

Just follow the docs https://docs.openfaas.com/ for your platform or see openfaas/faas-cli

Alex
