### ISSUE TITLE
Lab 6 - list.html not found 

### ISSUE THREAD

**Issue by padiazg** [openfaas/workshop#83]
When in the section `Read and return a static HTML file from disk` and you reach `Now we're going to add a path to the function URL.`, if you request `http://127.0.0.1:8080/function/show-html/list`, there is an error:
```
exit status 1
Traceback (most recent call last):
  File "index.py", line 18, in <module>
    ret = handler.handle(st)
  File "/home/app/function/handler.py", line 12, in handle
    with(open(page, 'r')) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/app/function/html/list.html'
```
I think it's because at this point there is still no `list.html`, which is created in the next section.

**Comment by martindekov** [comment]
Actually the lab6 misses the list.html file being created I will fix that thanks for the feedback @padiazg
