### ISSUE TITLE
Point out to the right directories

### ISSUE THREAD

**Issue by ivanayov** [openfaas/workshop#87]
During live workshop several people had this problem:

1. Creating a function in lab X in folder `labX`
2. Going to lab X + 1 where changes to the same function are required, but the contents are copied to `labX+1/` folder
3. Having editor still open with `labX` and doing the changes there by mistake.
4. Changes not applied 

It's an easy to find problem, but we may still think how to create better experience

**Comment by alexellis** [comment]
Derek close
