### ISSUE TITLE
Lab 4 | Error when no text present

### ISSUE THREAD

**Issue by divandauth** [openfaas/workshop#91]
During our workshop a couple of us had the following issue:

When calling the function after making all the changes in lab 4, it fails when there is no text present.

Perhaps you can add a note to remind users to always have text present when calling the sentimentanalysis function.

**Comment by rgee0** [comment]
Could you point me where you are finding an instruction to send no text to sentimentanalysis?  I've found this in Lab 4:

```
The Sentiment Analysis function will tell you the subjectivity and polarity (positivity rating) of any sentence. The result of the function is formatted in JSON as per the example below:

$ echo -n "California is great, it's always sunny there." | faas-cli invoke sentimentanalysis
{"polarity": 0.8, "sentence_count": 1, "subjectivity": 0.75}
```

Is the suggestion that we need to be explicit about the sentence being non-zero in length?

**Comment by rgee0** [comment]
Derek close: inactive
