### ISSUE TITLE
Lab8 - has a missing "up" command

### ISSUE THREAD

**Issue by neotrinity** [openfaas/workshop#92]
![image](https://user-images.githubusercontent.com/727843/48907268-3b602900-ee67-11e8-9d5a-f92d106dff77.png)

build, push, deploy and invoke functions skips "up" step.

`$ faas-cli up -f ./sleep-for.yml`
could be added.

**Comment by ewilde** [comment]
@neotrinity welcome to OpenFaaS. Hope you enjoyed going through the workshops. Great suggestion! perhaps the documentation should include the `up` cli command as you suggest.

Would you like to open a PR and make this change? Please see our [community guidelines for PR contributions](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#paperwork-for-pull-requests).

**Comment by alexellis** [comment]
The command isn't missing, so I'm going to close the issue.

`build/push/deploy` are the same as `up`.

Happy to take a PR as per Ed's recommendations.
